export const GENRE_CREATE_REQUEST = 'GENRE_CREATE_REQUEST';
export const GENRE_CREATE_SUCCESS = 'GENRE_CREATE_SUCCESS';
export const GENRE_CREATE_FAIL = 'GENRE_CREATE_FAIL';
export const GENRE_CREATE_RESET = 'GENRE_CREATE_RESET';

export const GENRE_LIST_REQUEST = 'GENRE_LIST_REQUEST';
export const GENRE_LIST_SUCCESS = 'GENRE_LIST_SUCCESS';
export const GENRE_LIST_FAIL = 'GENRE_LIST_FAIL';
export const GENRE_LIST_RESET = 'GENRE_LIST_RESET';

export const GENRE_DETAILS_REQUEST = 'GENRE_DETAILS_REQUEST';
export const GENRE_DETAILS_SUCCESS = 'GENRE_DETAILS_SUCCESS';
export const GENRE_DETAILS_FAIL = 'GENRE_DETAILS_FAIL';
