export const GENRE_CREATE_REQUEST = 'GENRE_CREATE_REQUEST';
export const GENRE_CREATE_SUCCESS = 'GENRE_CREATE_SUCCESS';
export const GENRE_CREATE_FAIL = 'GENRE_CREATE_FAIL';
export const GENRE_CREATE_RESET = 'GENRE_CREATE_RESET';

export const GENRE_LIST_REQUEST = 'GENRE_LIST_REQUEST';
export const GENRE_LIST_SUCCESS = 'GENRE_LIST_SUCCESS';
export const GENRE_LIST_FAIL = 'GENRE_LIST_FAIL';
export const GENRE_LIST_RESET = 'GENRE_LIST_RESET';

export const GENRE_DETAILS_REQUEST = 'GENRE_DETAILS_REQUEST';
export const GENRE_DETAILS_SUCCESS = 'GENRE_DETAILS_SUCCESS';
export const GENRE_DETAILS_FAIL = 'GENRE_DETAILS_FAIL';
export const GENRE_DETAILS_RESET = 'GENRE_DETAILS_RESET';

export const GENRE_UPDATE_REQUEST = 'GENRE_UPDATE_REQUEST';
export const GENRE_UPDATE_SUCCESS = 'GENRE_UPDATE_SUCCESS';
export const GENRE_UPDATE_FAIL = 'GENRE_UPDATE_FAIL';
export const GENRE_UPDATE_RESET = 'GENRE_UPDATE_RESET';

export const GENRE_DELETE_REQUEST = 'GENRE_DELETE_REQUEST';
export const GENRE_DELETE_SUCCESS = 'GENRE_DELETE_SUCCESS';
export const GENRE_DELETE_FAIL = 'GENRE_DELETE_FAIL';
